name: Unit Tests

on: [push, pull_request]

jobs:
  linter:
    name: Indentation Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
    - name: Lint with pylint
      run: |
        python -m pylint --disable=all -e W0311 --jobs=0 --indent-string='    ' **/*.py

  unittest:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install toml
        python -c "import toml; c = toml.load('pyproject.toml');
        dependencies = c['tool']['poetry']['dependencies'];
        print('\n'.join(dependencies).replace('python', ''))" |
          pip install -r /dev/stdin
    - name: Run unittest
      run: |
        python3 -m unittest -v
