name: unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Download dataset
      run: |
        mkdir data/
        wget http://ergast.com/downloads/f1db_csv.zip
        unzip -d data f1db_csv.zip
        rm f1db_csv.zip
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2
    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}
    - name: Set Poetry config
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs
    - name: Install dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Run unittest
      run: |
        poetry run python3 -m unittest
